apiVersion: v1
kind: Pod
metadata:
  name: nodejs-pod
spec:
  containers:
    - name: nodejs-container
      image: node:14  # Replace with your desired Node.js version
      command:
        - cat
      tty: true
